name: Toric
version: 1.9.1
date: 03/02/2017
description: toric varieties and some combinatorial geometry computations

authors:
    - name: David Joyner
      url: https://sites.google.com/site/wdjoyner/toric

maintainers:
    - name: David Joyner
      url: https://sites.google.com/site/wdjoyner/toric

GAP: ">= 4.5"

www: https://gap-packages.github.io/Toric
readme: https://gap-packages.github.io/Toric/README.md
packageinfo: https://gap-packages.github.io/Toric/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Toric/releases/download/v1.9.1/Toric-1.9.1.tar.gz

abstract: <span class="pkgname">toric</span> is a <span class="pkgname">GAP</span>package for computing with toric varieties.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
