name: Toric
version: 1.9.4
date: 07/03/2017
description: toric varieties and some combinatorial geometry computations

authors:
    - name: David Joyner
      url: https://sites.google.com/site/wdjoyner/

maintainers:
    - name: David Joyner
      url: https://sites.google.com/site/wdjoyner/

GAP: ">= 4.5"

www: https://gap-packages.github.io/toric
readme: README.md
packageinfo: https://gap-packages.github.io/toric/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/toric/releases/download/v1.9.4/Toric-1.9.4.tar.gz

abstract: <span class="pkgname">toric</span> is a <span class="pkgname">GAP</span>package for computing with toric varieties.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
